a           href        URI
area        href        URI
link        href        URI
img         src         URI
img         longdesc    URI
img         usemap      URI
object      classid     URI
object      codebase    URI
object      data        URI
object      archive     URILIST
object      usemap      URI
applet      codebase    URI
applet      archive     URILIST
q           cite        URI
blockquote  cite        URI
ins         cite        URI
del         cite        URI
form        action      URI
input       src         URI
input       usemap      URI
head        profile     URI
base        href        URI
script      src         URI
script      for         URI
