link        ref                 URI
blockquote  cite                URI
a           href                URI
ins         cite                URI
del         cite                URI
img         src                 URI
iframe      src                 URI
embed       src                 URI
object      data                URI
video       src                 URI
video       poster              URI
audio       src                 URI
source      src                 URI
track       src                 URI
area        href                URI
form        action              URI
input       formaction          URI
input       src                 URI
button      formaction          URI
script      src                 URI
# PINGURI http://www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#ping
a           ping                PINGURI
area        ping                PINGURI 

# SRCSET http://www.whatwg.org/specs/web-apps/current-work/multipage/embedded-content.html#image-candidate-string
img         srcset              SRCSET 
source      srcset              SRCSET 

# TODO find form submit states and form-action resources separately
form        action              FORM
input       formaction          FORM
button      formaction          FORM

body        onafterprint        SCRIPT
body        onbeforeprint       SCRIPT
body        onbeforeunload      SCRIPT
body        onhashchange        SCRIPT
body        onlanguagechange    SCRIPT
body        onmessage           SCRIPT
body        onoffline           SCRIPT
body        ononline            SCRIPT
body        onpagehide          SCRIPT
body        onpageshow          SCRIPT
body        onpopstate          SCRIPT
body        onstorage           SCRIPT
body        onunload            SCRIPT
*           onabort             SCRIPT
*           onautocomplete      SCRIPT
*           onautocompleteerror SCRIPT
*           onblur              SCRIPT
*           oncancel            SCRIPT
*           oncanplay           SCRIPT
*           oncanplaythrough    SCRIPT
*           onchange            SCRIPT
*           onclick             SCRIPT
*           onclose             SCRIPT
*           oncontextmenu       SCRIPT
*           oncuechange         SCRIPT
*           ondblclick          SCRIPT
*           ondrag              SCRIPT
*           ondragend           SCRIPT
*           ondragenter         SCRIPT
*           ondragexit          SCRIPT
*           ondragleave         SCRIPT
*           ondragover          SCRIPT
*           ondragstart         SCRIPT
*           ondrop              SCRIPT
*           ondurationchange    SCRIPT
*           onemptied           SCRIPT
*           onended             SCRIPT
*           onerror             SCRIPT
*           onfocus             SCRIPT
*           oninput             SCRIPT
*           oninvalid           SCRIPT
*           onkeydown           SCRIPT
*           onkeypress          SCRIPT
*           onkeyup             SCRIPT
*           onload              SCRIPT
*           onloadeddata        SCRIPT
*           onloadedmetadata    SCRIPT
*           onloadstart         SCRIPT
*           onmousedown         SCRIPT
*           onmouseenter        SCRIPT
*           onmouseleave        SCRIPT
*           onmousemove         SCRIPT
*           onmouseout          SCRIPT
*           onmouseover         SCRIPT
*           onmouseup           SCRIPT
*           onmousewheel        SCRIPT
*           onpause             SCRIPT
*           onplay              SCRIPT
*           onplaying           SCRIPT
*           onprogress          SCRIPT
*           onratechange        SCRIPT
*           onreset             SCRIPT
*           onresize            SCRIPT
*           onscroll            SCRIPT
*           onseeked            SCRIPT
*           onseeking           SCRIPT
*           onselect            SCRIPT
*           onshow              SCRIPT
*           onsort              SCRIPT
*           onstalled           SCRIPT
*           onsubmit            SCRIPT
*           onsuspend           SCRIPT
*           ontimeupdate        SCRIPT
*           ontoggle            SCRIPT
*           onvolumechange      SCRIPT
*           onwaiting           SCRIPT

*           style               CSS
